# Generated by Django 5.1.3 on 2025-03-02 09:55

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_group_uuid_cardtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='priority',
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(related_name='card_tags', to='group.cardtag'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
