# Generated by Django 5.1.3 on 2024-12-08 06:53

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_group_uuid_grouptag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, upload_to='group_icons/'),
        ),
    ]
