# Generated by Django 5.1.3 on 2025-03-02 10:25

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_group_uuid_columnboard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='columnboard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.AddField(
            model_name='card',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='group.columnboard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='columnboard',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='group.group', to_field='group_uuid'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AddConstraint(
            model_name='columnboard',
            constraint=models.UniqueConstraint(fields=('name', 'group'), name='unique_column_name_per_group'),
        ),
    ]
