# Generated by Django 5.1.3 on 2025-01-22 06:07

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_grouptag_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptag',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
